export const PORT = 5000;

export const SOCKET_ACTIONS = {
  JOIN: "JOIN",
  JOINED: "JOINED",
  DISCONNECTED: "DISCONNECTED",
  CODE_CHANGE: "CODE_CHANGE",
  SYNC_CODE: "SYNC_CODE",
  LEAVE: "LEAVE",
};
